spring:
  application:
    name: payment-service
server:
  port: ${SERVER_PORT:8082}
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
