import '@testing-library/jest-dom/vitest'
import { fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { describe, expect, it, vi } from 'vitest'
import { App, expectedInvariant, grafanaDashboardUrl, grafanaTraceUrl, traceEvidence, traceUrl } from './App'
import { isLiveLabOnline, offlineLiveLabMessage, PortfolioTour } from './PortfolioTour'

describe('EventLab experiment console', () => {
  it('presents the executable baseline and the three planned failure scenarios', () => {
    render(<App />)

    const runButtons = screen.getAllByRole('button', { name: /run experiment/i })
    expect(runButtons).toHaveLength(5)
    expect(runButtons[0]).toBeEnabled()
    expect(screen.getByRole('heading', { name: 'Successful payment workflow' })).toBeInTheDocument()
    expect(screen.getByRole('heading', { name: 'Duplicate payment result' })).toBeInTheDocument()
    expect(screen.getByRole('heading', { name: 'Fulfilment unavailable' })).toBeInTheDocument()
    expect(screen.getByRole('heading', { name: 'Fulfilment rejected' })).toBeInTheDocument()
    expect(screen.getByRole('heading', { name: 'Out-of-order update' })).toBeInTheDocument()
    expect(screen.getByRole('heading', { name: 'Compose a real experiment' })).toBeInTheDocument()
    expect(screen.getByRole('combobox', { name: 'Payment-result deliveries' })).toBeInTheDocument()
    expect(screen.getByRole('combobox', { name: 'Fulfilment behavior' })).toBeInTheDocument()
  })

  it('explains the invariant generated by a combined plan', () => {
    expect(expectedInvariant({ paymentResultDeliveries: 2, fulfilmentBehavior: 'BUSINESS_REJECTION' })).toBe(
      'Two payment-result deliveries produce one payment state change; the payment is compensated and the workflow ends COMPENSATED.',
    )
  })

  it('reveals and scrolls to the live experiment after launch', async () => {
    const scrollIntoView = vi.fn()
    const originalScrollIntoView = HTMLElement.prototype.scrollIntoView
    HTMLElement.prototype.scrollIntoView = scrollIntoView
    vi.spyOn(globalThis, 'fetch').mockImplementation(() => new Promise(() => {}))

    render(<App />)
    fireEvent.click(screen.getAllByRole('button', { name: /run experiment/i })[0])

    expect(screen.getByRole('heading', { name: 'Workflow in progress' })).toBeInTheDocument()
    await waitFor(() => expect(scrollIntoView).toHaveBeenCalledWith({ behavior: 'smooth', block: 'start' }))

    vi.restoreAllMocks()
    HTMLElement.prototype.scrollIntoView = originalScrollIntoView
  })

  it('builds a Grafana Explore link that looks up a trace by ID', () => {
    const url = new URL(grafanaTraceUrl('0123456789abcdef'))
    const left = JSON.parse(url.searchParams.get('left') ?? '{}')

    expect(left.datasource).toBe('tempo')
    expect(left.queries).toEqual([
      { query: '0123456789abcdef', queryType: 'traceql' },
    ])
    expect(left.range).toEqual({ from: 'now-1h', to: 'now' })
  })

  it('uses the runtime Grafana instance when configured', () => {
    const url = traceUrl('0123456789abcdef', 'https://grafana.example.test')

    expect(url).toMatch(/^https:\/\/grafana\.example\.test\/explore\?left=/)
    expect(decodeURIComponent(url)).toContain('0123456789abcdef')
  })

  it('links to the provisioned operations dashboard', () => {
    expect(grafanaDashboardUrl('https://grafana.example.test')).toBe(
      'https://grafana.example.test/d/eventlab-operations/eventlab-operations?from=now-1h&to=now',
    )
  })

  it('maps invariant claims to explicit trace evidence', () => {
    expect(traceEvidence('DUPLICATE_IGNORED')).toEqual({
      span: 'eventlab.workflow.inbox.decision',
      decision: 'DUPLICATE_IGNORED',
    })
    expect(traceEvidence('STALE_IGNORED')).toEqual({
      span: 'eventlab.workflow.version.decision',
      decision: 'STALE_IGNORED',
    })
    expect(traceEvidence('COMPLETED')).toBeUndefined()
  })

  it('renders a backend-independent portfolio tour', () => {
    const tour = render(<PortfolioTour />)
    const page = within(tour.container)

    expect(page.getByRole('heading', { name: /reliable messaging/i })).toBeInTheDocument()
    expect(page.getByRole('heading', { name: 'What each experiment proves' })).toBeInTheDocument()
    expect(page.getByText(/STALE_IGNORED · received 1 · current 2/)).toBeInTheDocument()
    expect(page.getByRole('heading', { name: 'Watch the invariant emerge' })).toBeInTheDocument()
    expect(page.getByRole('heading', { name: 'Correct under pressure' })).toBeInTheDocument()
    expect(page.getByText('1.55 s')).toBeInTheDocument()
    expect(page.getByText('5 / 5')).toBeInTheDocument()
    expect(page.getByText('2 → 1')).toBeInTheDocument()
    expect(page.getAllByRole('link', { name: 'Inspect result and method ↗' })).toHaveLength(3)
    expect(page.getAllByRole('img', { name: /EventLab timeline recording/ })).toHaveLength(3)
    expect(page.queryByRole('button', { name: /run experiment/i })).not.toBeInTheDocument()
  })

  it('enlarges and closes a recorded demonstration', () => {
    const tour = render(<PortfolioTour />)
    const page = within(tour.container)

    fireEvent.click(page.getByRole('button', { name: 'Enlarge Duplicate suppression recording' }))
    expect(page.getByRole('dialog', { name: 'Duplicate suppression enlarged recording' })).toBeInTheDocument()

    fireEvent.keyDown(document, { key: 'Escape' })
    expect(page.queryByRole('dialog')).not.toBeInTheDocument()
  })

  it('only advertises an active, unexpired live lab', () => {
    expect(isLiveLabOnline({
      state: 'online',
      url: 'https://eventlab.example.test',
      expiresAt: '2026-08-12T12:00:00Z',
    }, Date.parse('2026-08-12T11:00:00Z'))).toBe(true)
    expect(isLiveLabOnline({
      state: 'online',
      url: 'https://eventlab.example.test',
      expiresAt: '2026-08-12T12:00:00Z',
    }, Date.parse('2026-08-12T13:00:00Z'))).toBe(false)
    expect(isLiveLabOnline({ state: 'offline' })).toBe(false)
  })

  it('makes clear that offline deployments are owner-operated', () => {
    expect(offlineLiveLabMessage).toBe('Live lab offline · deployments are owner-operated')
  })
})
