create table timeline_events (
    sequence_number bigint generated by default as identity primary key,
    id uuid not null unique,
    workflow_id uuid not null,
    event_type varchar(100) not null,
    service_name varchar(50) not null,
    state varchar(50) not null,
    description varchar(500) not null,
    occurred_at timestamp with time zone not null,
    observed_at timestamp with time zone not null,
    trace_id varchar(32),
    payload_json text not null
);

create index timeline_events_workflow_sequence_idx
    on timeline_events (workflow_id, sequence_number);
